#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build raspberry pi 3b imwrt 24.10.0 actions.

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 4 * * *'

env:
  # immortalwrt 2410
  IMWRT2410_REPO_URL: ${{ secrets.IMWRT2410_REPO_URL }}
  IMWRT2410_REPO_BRANCH: ${{ secrets.IMWRT2410_REPO_BRANCH }}
  IMWRT2410_REPO_PATCH: ${{ secrets.IMWRT2410_REPO_PATCH }}
  # virtual machines x64
  RP3B_IMWRT2410_HOSTNAME: ${{ secrets.RP3B_IMWRT2410_HOSTNAME }}
  RP3B_IMWRT2410_PACKAGE: ${{ secrets.RP3B_IMWRT2410_PACKAGE }}
  RP3B_IMWRT2410_CONFIG: ${{ secrets.RP3B_IMWRT2410_CONFIG }}
  # feeds source
  ADD_FEED_SOURCE: ${{ secrets.ADD_FEED_SOURCE }}
  # diy script
  FIRMWARE_DIY_SCRIPT: ${{ secrets.FIRMWARE_DIY_SCRIPT }}
  # cmcc color theme
  ARGON_THEME_RPI: ${{ secrets.ARGON_THEME_RPI }}
  # token
  ACCESS_SHA512SUM: ${{ secrets.ACCESS_SHA512SUM }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  # telegram bot
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  # upload options
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  CACHE_TOOLCHAIN: true
  # hardware & repo info
  DEVICE_NAME: Raspberry-Pi_3B
  CPU_TAG: bcm2710
  FLASH_TAG: TF_8Gb
  SOURCE_CODE: immortalwrt
  OUTPUT_FILENAME: immortalwrt-2410-snakesan-bcm2710-rpi-3-sysupgrade
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - name: Checkout (ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ)
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Free Disk Space (ãƒãƒ¼ãƒ‰ãƒ‰ãƒ©ã‚¤ãƒ–ã®ç©ºãå®¹é‡ã‚’å¢—ã‚„ã™)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Check Server Performance (ã‚µãƒ¼ãƒãƒ¼ã®ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã‚’ç¢ºèªã™ã‚‹)
      run: |
        echo "âš ï¸è­¦å‘Šã™ã‚‹âš ï¸"
        echo "å‰²ã‚Šå½“ã¦ã‚‰ã‚ŒãŸã‚µãƒ¼ãƒãƒ¼ã®ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã«ã¯åˆ¶é™ãŒã‚ã‚Šã¾ã™ã€‚ãƒ—ãƒ©ã‚°ã‚¤ãƒ³ã‚’é¸æŠã—ã™ãã‚‹å ´åˆã¯ã€CPU ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã«æ³¨æ„ã—ã¦ãã ã•ã„ã€‚"
        echo -e "æ—¢çŸ¥ã®CPUãƒ¢ãƒ‡ãƒ«ï¼ˆé™é †ï¼‰: 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
        echo "-------------------------CPU æƒ…å ±---------------------------"
        echo "CPUã®ç‰©ç†æ•°  : $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUã‚³ã‚¢æ•°    : $(nproc)"
        echo -e "CPUãƒ¢ãƒ‡ãƒ«æƒ…å ±:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "------------------------ãƒ¡ãƒ¢ãƒªæƒ…å ±--------------------------"
        echo "ãƒ¡ãƒ¢ãƒªã®è©³ç´°:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "---------------------ãƒãƒ¼ãƒ‰ãƒ‡ã‚£ã‚¹ã‚¯æƒ…å ±---------------------"
        echo "ãƒãƒ¼ãƒ‰ãƒ‡ã‚£ã‚¹ã‚¯å®¹é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

#    - name: Combine Disks (ãƒ‡ã‚£ã‚¹ã‚¯ã‚’çµåˆã™ã‚‹)
#      uses: easimon/maximize-build-space@master
#      with:
#        swap-size-mb: 2048
#        temp-reserve-mb: 100
#        root-reserve-mb: 25600

    - name: Initialization environment (åˆæœŸåŒ–ç’°å¢ƒ)
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -yqq update
        sudo -E apt -yqq full-upgrade
        sudo -E apt -yqq autoremove --purge
        sudo -E apt -yqq autoclean
        sudo -E apt -yqq clean
        sudo -E apt -yqq install zip rename dos2unix libfuse-dev
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E systemctl daemon-reload
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code (ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã®ã‚¯ãƒ­ãƒ¼ãƒ³)
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $IMWRT2410_REPO_URL -b $IMWRT2410_REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        ${{ secrets.ADD_FEED_SOURCE }}

        # Remove All China download sources (ä¸­å›½ã‹ã‚‰ã®ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã‚½ãƒ¼ã‚¹ã‚’å‰Šé™¤ã™ã‚‹)
        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
        if [ -f "$PROJECT_MIRRORS_FILE" ]; then
          sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
        fi

    - name: Generate Variables (å¤‰æ•°ã‚’ç”Ÿæˆã™ã‚‹)
      run: |
        SOURCE_REPO="$(echo $IMWRT2410_REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV

    - name: Cache Toolchain (ã‚­ãƒ£ãƒƒã‚·ãƒ¥ãƒ„ãƒ¼ãƒ«ãƒã‚§ãƒ¼ãƒ³)
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ secrets.IMWRT2410_REPO_BRANCH }}-${{ env.DEVICE_NAME }}
        prefix: ${{ github.workspace }}/openwrt

    - name: Updata & install feeds (ã‚¢ãƒƒãƒ—ãƒ‡ãƒ¼ãƒˆã¨ãƒ•ã‚£ãƒ¼ãƒ‰ã®ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«)
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang
        git clone https://github.com/sbwml/packages_lang_golang -b 24.x feeds/packages/lang/golang
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Load custom configuration (ã‚«ã‚¹ã‚¿ãƒ æ§‹æˆã‚’èª­ã¿è¾¼ã‚€)
      run: |
        ${{ secrets.RP3B_IMWRT2410_CONFIG }}
        mv .config openwrt/.config
        cd openwrt
        ${{ secrets.IMWRT2410_REPO_PATCH }}
        ${{ secrets.FIRMWARE_DIY_SCRIPT }}
        ${{ secrets.RP3B_IMWRT2410_HOSTNAME }}
        ${{ secrets.ARGON_THEME_RPI }}

    - name: Download package (ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã‚’ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰)
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware (ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã‚’ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã™ã‚‹)
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: View Disk Usage (ãƒ‡ã‚£ã‚¹ã‚¯ä½¿ç”¨é‡ã®è¡¨ç¤º)
      if: (!cancelled())
      run: df -hT

    - name: Telegram notify when compilation error (ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã‚¨ãƒ©ãƒ¼ãŒç™ºç”Ÿã—ãŸã¨ãã«ãƒ†ãƒ¬ã‚°ãƒ©ãƒ ã‚’ä½¿ç”¨ã—ã¦é€šçŸ¥ã™ã‚‹)
      if: steps.compile.outputs.status != 'success' && !cancelled()
      env:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        curl -i -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=âŒ%20ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã«å¤±æ•—ã—ã¾ã—ãŸï¼%20âŒ%0A%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0Aãƒ»ğŸ›œæ”¯æ´ãƒ‡ãƒã‚¤ã‚¹:%0Aã€€%20ã€€${{ env.DEVICE_NAME }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ’½ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯:%0Aã€€%20ã€€${{ env.FLASH_TAG }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰:%0Aã€€%20ã€€${{ env.SOURCE_CODE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“¦ãƒªãƒã‚¸ãƒˆãƒªã‚’:%0Aã€€%20ã€€${{ env.SOURCE_REPO }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ—ƒãƒ–ãƒ©ãƒ³ãƒåå‰:%0Aã€€%20ã€€${{ secrets.IMWRT2410_REPO_BRANCH }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»âŒã‚¨ãƒ©ãƒ¼ã®æ™‚é–“:%0Aã€€%20ã€€$(date +'%Yå¹´%mæœˆ%dæ—¥_%Hæ™‚%Måˆ†')%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0A"

    - name: Organize files (ãƒ•ã‚¡ã‚¤ãƒ«ã‚’æ•´ç†ã™ã‚‹)
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        ls | grep -v *.gz | xargs rm -rdf
        mv *.gz ${{ env.OUTPUT_FILENAME }}.gz
        sha512sums -qq -r -P ${{ secrets.ACCESS_SHA512SUM }} sha512sums ${{ env.OUTPUT_FILENAME }}.gz
        ${{ secrets.RP3B_IMWRT2410_PACKAGE }}
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware To Artifact (Artifactã«ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.OUTPUT_FILENAME }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Telegram notify when compilation complete (ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ãŸã‚‰ãƒ†ãƒ¬ã‚°ãƒ©ãƒ ã‚’ä½¿ç”¨ã—ã¦é€šçŸ¥ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        curl -i -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=âœ…%20ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ã¾ã—ãŸï¼%20âœ…%0A%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0Aãƒ»ğŸ›œæ”¯æ´ãƒ‡ãƒã‚¤ã‚¹:%0Aã€€%20ã€€${{ env.DEVICE_NAME }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ’½ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯:%0Aã€€%20ã€€${{ env.FLASH_TAG }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰:%0Aã€€%20ã€€${{ env.SOURCE_CODE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“¦ãƒªãƒã‚¸ãƒˆãƒªã‚’:%0Aã€€%20ã€€${{ env.SOURCE_REPO }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ—ƒãƒ–ãƒ©ãƒ³ãƒåå‰:%0Aã€€%20ã€€${{ secrets.IMWRT2410_REPO_BRANCH }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ãƒ•ã‚¡ã‚¤ãƒ«åå‰:%0Aã€€%20ã€€${{ env.OUTPUT_FILENAME}}_${{ env.FILE_DATE }}%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0A"

    - name: Generate Release Tag (ã‚¿ã‚°ã‚’ç”Ÿæˆã™ã‚‹)
      run: |
        RELEASE_TAG="$CPU_TAG-$DEVICE_NAME-$FLASH_TAG-$FILE_DATE"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

    - name: Upload Firmware To Release (ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã‚’ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.CPU_TAG }}_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        allowUpdates: false
        tag: ${{ env.RELEASE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}/*
        body: |
          **ã“ã®ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã¯ã€CPUã€Œ${{ env.CPU_TAG }}ã€ãƒ¢ãƒ‡ãƒ«ã€Œ${{ env.DEVICE_NAME }}ã€ã‚’æ­è¼‰ã—ãŸãƒ«ãƒ¼ã‚¿ãƒ¼âœ… ${{ env.FLASH_TAG }} âœ…ã«ã®ã¿é©ã—ã¦ã„ã¾ã™ã€‚**
          ### ğŸ“’ã€Œ${{ env.SOURCE_CODE }}ã€ãƒªãƒã‚¸ãƒˆãƒªã®ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã‹ã‚‰ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã•ã‚ŒãŸãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã€‚
          - ğŸ›œ æ”¯æ´ãƒ‡ãƒã‚¤ã‚¹: ${{ env.DEVICE_NAME }}
          - ğŸ“ ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰: ${{ env.SOURCE_CODE }}
          - ğŸ“¦ ãƒªãƒã‚¸ãƒˆãƒªã‚’: ${{ env.SOURCE_REPO }}
          - ğŸ—ƒ ãƒ–ãƒ©ãƒ³ãƒåå‰: ${{ secrets.IMWRT2410_REPO_BRANCH }}
          - ğŸŒ æ¥ç¶šã‚¢ãƒ‰ãƒ¬ã‚¹: 192.168.***.1 ã¾ãŸã¯ anna.lan
          - ğŸ”‘ ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ã¯: ãªã—
          ### âš ï¸ è­¦å‘Šã™ã‚‹ âš ï¸
          - â€¼ï¸ç¾åœ¨ã®ãƒªãƒã‚¸ãƒˆãƒªã«ã‚ˆã£ã¦ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã•ã‚ŒãŸãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã¯ã™ã¹ã¦éå…¬é–‹ã§ã‚«ã‚¹ã‚¿ãƒã‚¤ã‚ºã•ã‚Œã¦ã„ã¾ã™ã€‚
          - â›”ï¸å¼·åˆ¶ãƒ•ãƒ©ãƒƒã‚·ãƒ¥â›”ï¸ã«ã‚ˆã£ã¦ãƒ‡ãƒã‚¤ã‚¹ãŒæå‚·ã—ãŸå ´åˆã€ã“ã®ãƒªãƒã‚¸ãƒˆãƒªã¯ãƒ‡ãƒã‚¤ã‚¹ã®æå‚·ã«ã¤ã„ã¦ä¸€åˆ‡è²¬ä»»ã‚’è² ã„ã¾ã›ã‚“ã€‚

    - name: Delete old workflow runs (å¤ã„ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼å®Ÿè¡Œã‚’å‰Šé™¤ã™ã‚‹)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 3

    - name: Delete Old Releases (å¤ã„ãƒªãƒªãƒ¼ã‚¹ã‚’å‰Šé™¤ã™ã‚‹)
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 15
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
